/* DO NOT EDIT THIS FILE - it is machine generated */
#include "C:\Users\DriapkoA\Documents\jni.h"
/* Header for class rtmath_containers_MemoryHelper */

#ifndef _Included_rtmath_containers_MemoryHelper
#define _Included_rtmath_containers_MemoryHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rtmath_containers_MemoryHelper
 * Method:    memMove
 * Signature: ([BI[JII)V
 */
JNIEXPORT void JNICALL Java_rtmath_containers_MemoryHelper_memMove
  (JNIEnv *, jclass, jbyteArray, jint, jlongArray, jint, jint);

/*
 * Class:     rtmath_containers_MemoryHelper
 * Method:    getByte
 * Signature: ([JI)B
 */
JNIEXPORT jbyte JNICALL Java_rtmath_containers_MemoryHelper_getByte
  (JNIEnv *, jclass, jlongArray, jint);

/*
 * Class:     rtmath_containers_MemoryHelper
 * Method:    setByte
 * Signature: ([JIB)V
 */
JNIEXPORT void JNICALL Java_rtmath_containers_MemoryHelper_setByte
  (JNIEnv *, jclass, jlongArray, jint, jbyte);



#ifdef __cplusplus
}
#endif
#endif
